version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ap-northeast-2  # 원하는 리전을 지정하세요.
    ECR_REPOSITORY_NAME: narrativa1  # ECR에 생성한 리포지토리 이름
    ECS_CLUSTER_NAME: narrativa1  # ECS 클러스터 이름
    ECS_SERVICE_NAME: narrativa1  # ECS 서비스 이름
  secrets-manager:
    REACT_APP_LLM: your-secrets-manager-key:REACT_APP_LLM
    REACT_APP_TTS: your-secrets-manager-key:REACT_APP_TTS

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Checking out dev branch...
      - git checkout dev
      - echo Pulling the latest dev branch...
      - git pull origin dev
      - echo Build started on `date`

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $ECR_REPOSITORY_NAME --build-arg REACT_APP_LLM=$REACT_APP_LLM --build-arg REACT_APP_TTS=$REACT_APP_TTS .
      - docker tag $ECR_REPOSITORY_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:latest

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:latest
      - echo Triggering ECS service update...
      - aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $ECS_SERVICE_NAME --force-new-deployment
    finally:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
